# Generated by Django 4.1.5 on 2023-02-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_state_crime_rank_state_crime_rate_state_home_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='tourism_site',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
