# Generated by Django 4.1.5 on 2023-01-25 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=25)),
                ('weighted_rank', models.SmallIntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
