# Generated by Django 4.1.5 on 2023-02-17 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etats', '0002_rank_delete_state'),
    ]

    operations = [
        migrations.DeleteModel('Rank')
    ]
